# Generated by Django 2.0.2 on 2018-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
