# Generated by Django 2.0.2 on 2018-03-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180304_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='civil_id',
            field=models.PositiveIntegerField(),
        ),
    ]
