# Generated by Django 2.0.2 on 2018-03-05 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20180305_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='individualprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualprofile',
            name='profile_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
