# Generated by Django 2.0.2 on 2018-03-11 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_person_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='squad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
